const $=s=>document.querySelector(s);let lessons=[],index=0,deferredPrompt;const audio=$('#audio');
async function start(){lessons=await fetch('data/lessons.json').then(r=>r.json());renderMenu();if('serviceWorker'in navigator){await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;downloadForOffline()}else $('#offlineState').textContent='Online mode only'}
async function downloadForOffline(){const label=$('#offlineState'),cache=await caches.open('chunk-loop-audio-v2'),urls=lessons.map(x=>new URL(`audio/${x.audio_filename}`,location.href).href);let done=0;for(const url of urls)if(await cache.match(url))done++;if(done===urls.length){label.textContent='Offline mode ready · 100/100';return}for(const url of urls){if(await cache.match(url))continue;label.textContent=`Saving audio for offline use… ${done}/100`;try{const r=await fetch(url);if(!r.ok)throw Error(r.status);await cache.put(url,r);done++}catch(e){label.textContent=`Download paused at ${done}/100 · keep this screen open`;return}}label.textContent='Offline mode ready · 100/100'}
function renderMenu(){const list=$('#lessonList');lessons.forEach((x,i)=>{const li=document.createElement('li'),b=document.createElement('button');b.innerHTML=`<span class="num">${String(x.id).padStart(3,'0')}</span><span class="lessonText">${esc(x.sentence)}<span class="chunk">${esc(x.target_chunk)}</span></span>`;b.onclick=()=>openLesson(i);li.append(b);list.append(li)})}
function openLesson(i){index=i;$('#menu').hidden=true;$('#study').hidden=false;$('#japanese').hidden=true;$('#translationToggle').textContent='日本語を表示';renderLesson();window.scrollTo(0,0)}
function renderLesson(){const x=lessons[index],p=x.sentence.toLowerCase().indexOf(x.target_chunk.toLowerCase());$('#sentence').innerHTML=p<0?esc(x.sentence):`${esc(x.sentence.slice(0,p))}<mark>${esc(x.sentence.slice(p,p+x.target_chunk.length))}</mark>${esc(x.sentence.slice(p+x.target_chunk.length))}`;$('#japanese').textContent=x.japanese;$('#counter').textContent=`${String(index+1).padStart(2,'0')} / ${lessons.length}`;audio.src=`audio/${x.audio_filename}`;audio.play().then(()=>setPlaying(true)).catch(()=>{setPlaying(false);$('#error').textContent='Playを押して音声を開始してください。'})}
function setPlaying(v){$('#play').textContent=v?'Pause':'Play';$('#playingState').textContent=v?'LOOPING':'PAUSED'}
$('#play').onclick=()=>{if(audio.paused)audio.play().then(()=>setPlaying(true));else{audio.pause();setPlaying(false)}};$('#next').onclick=()=>{index=(index+1)%lessons.length;renderLesson()};$('#back').onclick=()=>{audio.pause();$('#study').hidden=true;$('#menu').hidden=false};$('#translationToggle').onclick=()=>{const e=$('#japanese');e.hidden=!e.hidden;$('#translationToggle').textContent=e.hidden?'日本語を表示':'日本語を隠す'};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#install').hidden=false});$('#install').onclick=()=>deferredPrompt?.prompt();function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}start().catch(e=>{$('#offlineState').textContent='Could not load lessons';console.error(e)});
